name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.0  

    - name: Build an Application
      run: |
        dotnet build
    
    - name: Testing an ASP.NET Backend Application
      run: |
        dotnet test
